name: "jaffle_shop"
version: "1.0"
config-version: 2

profile: my_redshift_profile

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  marts:
    +materialized: table
  staging:
    +materialized: view
